services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: db_users
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - ./users/.env

  users_service:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users_service
    ports:
      - "8000:8000"
    volumes:
      - ./users:/app
    env_file:
      - ./users/.env
    depends_on:
      - db
    networks:
      - app-network       

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
